version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/go:1.17.8
    steps:
      - checkout
      - run:
          name: Install dependency
          command: go mod download
      - run:
          name: Run Tests
          command: go test ./test/...
      - run: go version