version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1

executors:
  go:
    docker:
      - image: cimg/go:1.17.8

workflows:
  build-and-deploy:
    jobs:
      - tests
      - ecr-build-and-push-image
      - aws-ecs/deploy-service-update:
          requires:
            - ecr-build-and-push-image
          aws-region: AWS_REGION
          family: 'sample-docker-gin-service100'
          cluster-name: 'sample-docker-gin-cluster10'
          container-image-name-updates: 'container=sample-docker-gin-service100,tag=${CIRCLE_SHA1}'

jobs:
  tests:
    executor:
      name: go
    steps:
      - checkout
      - run:
          name: Install dependency
          command: |
            cd ./docker/go/
            go mod download
      - run:
          name: Run Tests
          command: |
            cd ./docker/go/
            go test ./test/...
  ecr-build-and-push-image:
    executor:
      name: go
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          tag: "${CIRCLE_SHA1},latest"
          path: docker/go
          repo: "sample-docker-gin"
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          extra-build-args: "--target prod"
  ecs-deploy-service-update:
    executor:
      name: go
    steps:
      - aws-ecs/deploy-service-update:
          repo: "sample-docker-gin"
          tag: "${CIRCLE_SHA1},latest"
